Repository Shanki200801/milestone-monitor, pull requests merged in 2023-10, with the labels that each got.

#24 Dashboard is now responsive (where it matters, at least)
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components/dashboard/account.tsx
  components/dashboard/carousel.tsx
  components/dashboard/events.tsx
  components/nav/navOne.tsx
  components/nav/navTwo.tsx
  components/nav/navbar.tsx
  package-lock.json
  package.json
Labels: bug

#25 table displays data from backend. added all routes with auth
  app/input-forms/AddWorkshops.tsx
  app/modify/approvals/Approval.tsx
  app/modify/approvals/page.tsx
  app/modify/approvals/types.tsx
  app/my-journals/page.tsx
  app/my-patents/page.tsx
  app/my-workshops/page.tsx
  app/profile/page.tsx
  app/report-gen/ReportPage.tsx
  app/report-gen/page.tsx
Labels: enhancement

#29 Fixed layout issues regarding login page, create new route groups
  app/(generic)/input-forms/AddConference.tsx
  app/(generic)/input-forms/AddJournals.tsx
  app/(generic)/input-forms/AddPatents.tsx
  app/(generic)/input-forms/AddWorkshops.tsx
  app/(generic)/input-forms/InputCard.jsx
  app/(generic)/input-forms/page.tsx
  app/(generic)/layout.tsx
  app/(generic)/modify/approvals/Approval.tsx
  app/(generic)/modify/approvals/page.tsx
  app/(generic)/modify/approvals/types.tsx
  app/(generic)/modify/staff/add-staff/AddStaff.tsx
  app/(generic)/modify/staff/add-staff/page.tsx
  app/(generic)/my-conferences/MyConference.tsx
  app/(generic)/my-conferences/page.tsx
  app/(generic)/my-journals/MyJournals.tsx
  app/(generic)/my-journals/page.tsx
  app/(generic)/my-patents/MyPatents.tsx
  app/(generic)/my-patents/page.tsx
  app/(generic)/my-workshops/MyWorkshops.tsx
  app/(generic)/my-workshops/page.tsx
  app/(generic)/page.tsx
  app/(generic)/profile/Profile.tsx
  app/(generic)/profile/page.tsx
  app/(generic)/report-gen/ReportPage.tsx
  app/(generic)/report-gen/page.tsx
  app/(login)/login/layout.tsx
  app/(login)/login/page.tsx
  app/report-gen/ReportPage.tsx
Labels: bug

#30 Merge this to fix deployment errors.
  app/(generic)/layout.tsx
  app/(generic)/page.tsx
  app/(generic)/profile/Profile.tsx
  app/(generic)/profile/page.tsx
  components/dashboard/events.tsx
  components/nav/navOne.tsx
  components/nav/navTwo.tsx
  components/nav/navbar.tsx
  components/profile/Account.tsx
  components/profile/Settings.tsx
  components/profile/Socials.tsx
  public/pfp-placeholder.webp
Labels: bug

#31 Deployment fixes pt. 2 (I really hope this fixes stuff)
  components/dashboard/Account.tsx
  components/dashboard/Carousel.tsx
  components/dashboard/Events.tsx
  components/nav/NavOne.tsx
  components/nav/NavTwo.tsx
  components/nav/Navbar.tsx
Labels: bug

#34 17 category pages
  app/(categories)/layout.tsx
  app/(categories)/my-conferences/MyConference.tsx
  app/(categories)/my-conferences/page.tsx
  app/(categories)/my-journals/MyJournals.tsx
  app/(categories)/my-journals/page.tsx
  app/(categories)/my-patents/MyPatents.tsx
  app/(categories)/my-patents/page.tsx
  app/(categories)/my-workshops/MyWorkshops.tsx
  app/(categories)/my-workshops/page.tsx
  app/(generic)/my-conferences/MyConference.tsx
  app/(generic)/my-conferences/page.tsx
  app/(generic)/my-journals/MyJournals.tsx
  app/(generic)/my-patents/MyPatents.tsx
  app/(generic)/my-workshops/MyWorkshops.tsx
  app/api/dbfunctions.tsx
  components/categories/AddNewSec.tsx
  components/categories/CategoryHeader.tsx
  components/categories/NoData.tsx
Labels: enhancement

#37 Merge this to fix deployment errors. :)
  app/(profile)/profile/page.tsx
  app/(profile)/profile/test/Settings.tsx
  app/(profile)/profile/test/page.tsx
Labels: bug

#39 35 edit submissions
  app/(categories)/my-conferences/MyConference.tsx
  app/(categories)/my-journals/MyJournals.tsx
  app/(categories)/my-patents/MyPatents.tsx
  app/(categories)/my-workshops/MyWorkshops.tsx
  app/api/dbfunctions.tsx
  package-lock.json
  package.json
  tailwind.config.js
Labels: modification

#41 Completed individual filter queries for tables.
  app/api/dbfunctions.tsx
  app/test-route/page.tsx
  next.config.js
Labels: enhancement

#42 Fixed deployment error
  app/test-route/page.tsx
Labels: bug

#43 38 - Integrated Profile & Dashboard, Profile is now Settings, Minor style overhaul.
  app/(categories)/layout.tsx
  app/(categories)/my-conferences/MyConference.tsx
  app/(categories)/my-journals/MyJournals.tsx
  app/(categories)/my-patents/MyPatents.tsx
  app/(categories)/my-workshops/MyWorkshops.tsx
  app/(generic)/page.tsx
  app/(login)/login/page.tsx
  app/(settings)/settings/NavOne.tsx
  app/(settings)/settings/layout.tsx
  app/(settings)/settings/page.tsx
  components/categories/AddNewSec.tsx
  components/categories/CategoryHeader.tsx
  components/categories/NoData.tsx
  components/dashboard/Account.tsx
  components/dashboard/Carousel.tsx
  components/dashboard/Events.tsx
  components/nav/NavOne.tsx
  components/nav/NavTwo.tsx
  components/nav/Navbar.tsx
  components/profile/Account.tsx
  components/profile/Settings.tsx
Labels: modification

#45 28 create page for report generation
  app/(generic)/profile/Profile.tsx
  app/(generic)/profile/page.tsx
  app/(generic)/report-gen/CSVHeaders.tsx
  app/(generic)/report-gen/Filters.tsx
  app/(generic)/report-gen/GeneralTable.tsx
  app/(generic)/report-gen/ReportPage.tsx
  app/(generic)/report-gen/page.tsx
  app/(generic)/test/Test.tsx
  app/(generic)/test/page.tsx
  app/api/dbfunctions.tsx
  package-lock.json
  package.json
Labels: enhancement

#47 38 - Settings page update
  app/(generic)/test/Test.tsx
  app/(settings)/settings/page.tsx
  components/settings/Settings.tsx
  components/settings/Socials.tsx
Labels: bug, modification

#52 46 - Added Chart.js component to Dashboard.
  app/(generic)/page.tsx
  components/dashboard/Stats.tsx
  package-lock.json
  package.json
Labels: modification

#53 40 page authorization
  app/(categories)/my-conferences/MyConference.tsx
  app/(categories)/my-journals/MyJournals.tsx
  app/(categories)/my-patents/MyPatents.tsx
  app/(categories)/my-workshops/MyWorkshops.tsx
  app/(generic)/layout.tsx
  app/(generic)/modify/approvals/page.tsx
  app/(generic)/modify/page.tsx
  app/(generic)/modify/staff/add-staff/page.tsx
  app/(generic)/page.tsx
  app/(generic)/report-gen/page.tsx
  app/api/dbfunctions.tsx
  components/dashboard/Events.tsx
  components/nav/NavTwo.tsx
  components/nav/Navbar.tsx
Labels: enhancement

#55 added db fn for fetching stats and made some changes to add staf
  app/(generic)/modify/staff/add-staff/AddStaff.tsx
  app/api/dbfunctions.tsx
  components/categories/AddNewSec.tsx
  components/dashboard/DoughNutWrapper.tsx
  components/dashboard/Stats.tsx
  next.config.js
Labels: modification

#57 Minor styling mods to Dashboard & Nav Bar
  components/dashboard/Account.tsx
  components/dashboard/Events.tsx
  components/nav/NavTwo.tsx
  components/settings/Settings.tsx
Labels: modification

#67 Added some styling mods to Settings
  components/settings/Settings.tsx
Labels: modification

#68 58 Add achievement modals to all categories pages
  app/(categories)/my-conferences/MyConference.tsx
  app/(categories)/my-conferences/page.tsx
  app/(categories)/my-journals/MyJournals.tsx
  app/(categories)/my-journals/page.tsx
  app/(categories)/my-patents/MyPatents.tsx
  app/(categories)/my-patents/page.tsx
  app/(categories)/my-workshops/MyWorkshops.tsx
  app/(categories)/my-workshops/page.tsx
  app/(generic)/modify/staff/add-staff/page.tsx
  app/api/dbfunctions.tsx
  components/categories/AddNewSec.tsx
  components/nav/NavOne.tsx
Labels: bug

#71 Merge to fix deployment errors.
  app/(categories)/my-workshops/MyWorkshops.tsx
  app/(generic)/input-forms/AddConference.tsx
  app/(generic)/input-forms/AddJournals.tsx
  app/(generic)/input-forms/AddPatents.tsx
  app/(generic)/input-forms/AddWorkshops.tsx
  app/(generic)/input-forms/InputCard.jsx
  app/(generic)/input-forms/page.tsx
Labels: bug

#72 pfps of all extensions are now deleted before adding neww
  app/api/dbfunctions.tsx
  components/settings/Settings.tsx
Labels: bug
